Doing a modular project.
sergiogval/packing-js pull request #1
Opened 2022-01-18 01:53 UTC by sergiogval

This is the las step of the project.  I used two techniques to integrate modules to the index.js file on the root folder. The first one call the default export element of diferent files. the second one makes a list of elements to be exported.

2022-01-18 03:09 UTC, julie-ify requested changes
## Hi @sergiogval,

Good job so far!

## Highlight!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Good code organization and working app ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-18 03:09 UTC, julie-ify commented on README.md
> +- Instagram: [@sergioval](https://www.instagram.com/sergioval/)
- [ ] Good job with the README. However, let's have one author here as the project was built by one author which is you. This is to make the README more professional.

2022-01-18 03:09 UTC, julie-ify commented on README.md
> +- Open a terminal or a git bash in the desired directory and run git@github.com:sergiogval/package-js.git
- [ ] The best way to describe how to clone your repo is "Open a terminal or a git bash in the desired directory and run `git clone git@github.com:sergiogval/packing-js.git`"

2022-01-18 03:09 UTC, julie-ify commented on modules/index.js
> +export { default as today } from './time.js';
- [ ] We have already exported all these from their respective modules which is a nice implementation. I can see that you're exporting them here again and importing all of them in the `index.js` and the `index.js` has no implementation for now. 
- I would suggest deleting this file due to the repetition of the exports and just `import` these variables, functions, and class to the modules where you need them to prevent our code from being bulky and to keep our code `DRY` 😄.
- It is required that you use `export/import` for modules

2022-01-18 03:09 UTC, julie-ify commented on modules/logic.js
> +let books = new Array([]);
- [ ] Let's not disable linter checks as they make us write better codes. I suggest you use the array literal method 
`[] `  for simplicity, readability, and execution speed as there is no need to use `new Array()` method. See my suggestion below:

```suggestion
let books = [];
```

2022-01-18 03:09 UTC, julie-ify commented on modules/logic.js
> +let books = new Array([]);
- [ ] Currently, your app displays `undefined` for the `author` and `title` when you open the app before adding a book and the local storage shows an array inside of another array `[[]]` which I believe was caused by `new Array([]);`. Please let's fix this issue 👍.  To be able to see this bug, clear your local storage and open your app. See screenshot below:

<img width="866" alt="Loom_q3Ih8oN6A2" src="https://user-images.githubusercontent.com/81468675/149862017-1245409f-7dc2-4912-aa25-b7ec1b5dae87.png">

2022-01-18 03:09 UTC, julie-ify commented on modules/logic.js
> +};
Good use of `arrow` function syntax here. Keep rocking 🔥

2022-01-18 03:09 UTC, julie-ify commented on modules/time.js
> +export default today;
- [ ] Nice implementation of the date you have here. However, it is required that you use the [Luxon](https://moment.github.io/luxon/docs/manual/install.html) library to [Get the current date and time](https://moment.github.io/luxon/docs/manual/tour.html#get-the-current-date-and-time)

2022-01-18 03:09 UTC, julie-ify commented on modules/logic.js
> +  };
- [ ] The `addBook` and `removeBook` methods works. Keep rocking 💪. Since you used the arrow function syntax for the `addBook` method, wouldn't it be nice to use it for the `removeBook` method equally? What do you think?

2022-01-18 13:44 UTC, sergiogval commented on README.md
> +- Instagram: [@sergioval](https://www.instagram.com/sergioval/)
Done.

2022-01-18 13:46 UTC, sergiogval commented on README.md
> +- Open a terminal or a git bash in the desired directory and run git@github.com:sergiogval/package-js.git
You are right, I was missing a piece of code. Solved.

2022-01-18 13:56 UTC, sergiogval commented on modules/index.js
> +export { default as today } from './time.js';
I will follow this advice, but I'd like to stress that the utility of this is to hold all the elments to e exported in just one file and then then the index.js file on root folder make a 1 line call to this one.

2022-01-21 08:42 UTC, sergiogval commented on modules/index.js
> +export { default as today } from './time.js';
Is this completely mandatory? I mean, I believe that concentrate all exported components isn't that bad idea. Even it allows me to use the all modules folder by just calling this file using one line. It is practical. besides, in the index.js file that is hold on the root folder, I just use one line of code and it brought it all, i'm not repeating myself. Also, the code worked perfectly, plus this is a way to check what I am exporting just by looking one file in the all folder. Please consider this as an optional suggestion. Otherwise I will ask for a second opinion.

Regards.

2022-01-21 08:43 UTC, sergiogval commented on modules/logic.js
> +};
Thanks!

2022-01-21 08:48 UTC, sergiogval commented on modules/logic.js
> +  };
I think that I might do it. But it should be optional. This should be a nice to have, not a stopper to approve this PR. Please reconsider do this an optional change.

2022-01-21 10:11 UTC, sergiogval commented on modules/logic.js
> +let books = new Array([]);
![image](https://user-images.githubusercontent.com/67393791/150508009-3001c6b0-caab-4a97-a456-83c809565047.png)


If I follow this suggestion, it trow me an error. Honestly, I don't feel like you want to block me. But you definitively are. Please reconsider your review. My app was working flawless. Now is all broke. And I got no approval for this project.

2022-01-21 10:15 UTC, sergiogval commented on modules/logic.js
> +let books = new Array([]);
This project was approved like that. This is not in the scope of this milestone. Actually every one of the comments are welcome, but they are easily arguable.For instance, why would I use a dependency to get the time when it is already native on ES6? It has no sense, the output is exactly the same and it is a waste of time.

2022-01-21 11:01 UTC, mke2111 commented
Project Under Second Opinion Review.
Kindly wait for a response to come your way. 🙏🏽

2022-01-21 12:06 UTC, mke2111 reviewed
Hello @sergiogval  👋,

_This is an additional review as a result of the second opinion request._

Good job so far with your project. I personally like your approach of importing from a single file.

> In this review, I'll try to best explain the project requirements so that we all have the same point of view.

Consider the request of deleting the `modules/index.js` as optional. This is yet another way of having all exports in a single file and it's not a repetition of code.
About the `undefined` when there are no books, also consider this optional. But I also strongly suggest you give this a quick fix since it displays something you definitely don't want your app's users to see.
For this project, it is required that you use the Luxon library to get the current date. Treat this as a hard requirement.
It is also a requirement to use arrow fns syntax for all your fns including the `removeBook`. Treat this as a hard requirement.

Make all the mandatory requirements to meet all the project requirements. Submit another CRR once you have made all the changes.

Keep rocking 🚀 & Happy Coding 💻 !

2022-01-21 13:25 UTC, sergiogval commented
> Hello @sergiogval wave,
> 
> _This is an additional review as a result of the second opinion request._
> 
> Good job so far with your project. I personally like your approach of importing from a single file.
> 
> > In this review, I'll try to best explain the project requirements so that we all have the same point of view.
> 
> Consider the request of deleting the `modules/index.js` as optional. This is yet another way of having all exports in a single file and it's not a repetition of code. About the `undefined` when there are no books, also consider this optional. But I also strongly suggest you give this a quick fix since it displays something you definitely don't want your app's users to see. For this project, it is required that you use the Luxon library to get the current date. Treat this as a hard requirement. It is also a requirement to use arrow fns syntax for all your fns including the `removeBook`. Treat this as a hard requirement.
> 
> Make all the mandatory requirements to meet all the project requirements. Submit another CRR once you have made all the changes.
> 
> Keep rocking rocket & Happy Coding computer !

@mke2111 @julie-ify I really appreciate your willingness to help me out regarding be a better coder. I just have a quick question to have this crystal clear, the **RemoveBook" function is already done using modern JS syntax. So, may I consider that requirement as done and the only one that I am missing is to use as dependency the luxon library. I'm I right?

2022-01-21 13:39 UTC, mke2111 commented
Hi @sergiogval,  
It is true that ES6  `class` syntax supports static methods, and just like you have defined `  static addBook = (newBook) => ` and `   static displayBooks = () => `. You can as well maintain the arrow syntax with the `removeBook` to fullfil the project requirements.

2022-01-25 00:20 UTC, merged